name: Android CI

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-apk:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: gradle

      # Android SDK ist bereits vorinstalliert auf GitHub Runners.
      # Wir setzen nur die Umgebungsvariable und rufen sdkmanager DIREKT auf.
      - name: Accept licenses & install SDK packages
        shell: bash
        run: |
          export ANDROID_SDK_ROOT="/usr/local/lib/android/sdk"

          # Lizenzen akzeptieren (nicht interaktiv)
          yes | "$ANDROID_SDK_ROOT/cmdline-tools/16.0/bin/sdkmanager" --licenses

          # Benötigte Pakete installieren (ALLE ARGUMENTE IN *EINER* ZEILE!)
          "$ANDROID_SDK_ROOT/cmdline-tools/16.0/bin/sdkmanager" \
            "platform-tools" "platforms;android-34" "build-tools;34.0.0"

      # Build im Unterordner Lean9App ohne Wrapper (robust)
      - name: Build Debug APK
        uses: gradle/gradle-build-action@v3
        with:
          gradle-version: 8.8
          arguments: assembleDebug
          build-root-directory: Lean9App

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: Lean9App-debug
          path: Lean9App/app/build/outputs/apk/debug/app-debug.apk
