name: Android CI
on:
  push: { branches: [ "main" ] }
  workflow_dispatch:

jobs:
  build-apk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: gradle

      - name: Accept licenses & install SDK packages
        shell: bash
        run: |
          set -euxo pipefail
          export ANDROID_SDK_ROOT="/usr/local/lib/android/sdk"
          if [ -x "$ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager" ]; then
            SDKMANAGER="$ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager"
          else
            SDKMANAGER="$ANDROID_SDK_ROOT/cmdline-tools/16.0/bin/sdkmanager"
          fi
          yes | "$SDKMANAGER" --licenses
          "$SDKMANAGER" --install "platform-tools" "platforms;android-34" "build-tools;34.0.0" || \
          "$SDKMANAGER" --install "platform-tools" "platforms;android-35" "build-tools;35.0.0"

      - uses: gradle/gradle-build-action@v3
        with:
          gradle-version: 8.8
          arguments: assembleDebug
          build-root-directory: Lean9App

      - uses: actions/upload-artifact@v4
        with:
          name: Lean9App-debug
          path: Lean9App/app/build/outputs/apk/debug/app-debug.apk
