name: Android CI

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-apk:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: gradle

      # Nur cmdline-tools + Lizenzen, KEINE packages hier!
      - name: Set up Android SDK
        uses: android-actions/setup-android@v3
        with:
          accept-android-sdk-licenses: true
          cmdline-tools-version: 16.0

      # Installiere Pakete explizit in EINEM run-Step (eine Zeile, in Quotes)
      - name: Install required SDK packages
        shell: bash
        run: |
          sdkmanager "platform-tools" "platforms;android-34" "build-tools;34.0.0"

      # Baue im Unterordner Lean9App
      - name: Build Debug APK
        uses: gradle/gradle-build-action@v3
        with:
          gradle-version: 8.8
          arguments: assembleDebug
          build-root-directory: Lean9App

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: Lean9App-debug
          path: Lean9App/app/build/outputs/apk/debug/app-debug.apk
